USE master
GO
  CREATE DATABASE akademik COLLATE SQL_Latin1_General_CP1_CI_AS
GO
  USE akademik
GO
  CREATE TABLE [dbo].[Student] (
    [Id] INT NOT NULL IDENTITY (1, 1),
    [PokójId] INT NOT NULL,
    CONSTRAINT [PK_Student] PRIMARY KEY CLUSTERED (
      [Id] ASC
    ) WITH (
      PAD_INDEX = OFF,
      STATISTICS_NORECOMPUTE = OFF,
      IGNORE_DUP_KEY = OFF,
      ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON
    ) ON [PRIMARY]
  ) ON [PRIMARY]
GO
  CREATE TABLE [dbo].[Pokój] (
    [Id] INT NOT NULL IDENTITY (1, 1),
    CONSTRAINT [PK_Pokój] PRIMARY KEY CLUSTERED (
      [Id] ASC
    ) WITH (
      PAD_INDEX = OFF,
      STATISTICS_NORECOMPUTE = OFF,
      IGNORE_DUP_KEY = OFF,
      ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON
    ) ON [PRIMARY]
  ) ON [PRIMARY]
GO
  CREATE TABLE [dbo].[Studentka] (
    [Id] INT NOT NULL IDENTITY (1, 1),
    [RoomId] INT,
    CONSTRAINT [PK_Studentka] PRIMARY KEY CLUSTERED (
      [Id] ASC
    ) WITH (
      PAD_INDEX = OFF,
      STATISTICS_NORECOMPUTE = OFF,
      IGNORE_DUP_KEY = OFF,
      ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON
    ) ON [PRIMARY]
  ) ON [PRIMARY]
GO
  CREATE TABLE [dbo].[Room] (
    [Id] INT NOT NULL IDENTITY (1, 1),
    CONSTRAINT [PK_Room] PRIMARY KEY CLUSTERED (
      [Id] ASC
    ) WITH (
      PAD_INDEX = OFF,
      STATISTICS_NORECOMPUTE = OFF,
      IGNORE_DUP_KEY = OFF,
      ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON
    ) ON [PRIMARY]
  ) ON [PRIMARY]
GO
  CREATE UNIQUE NONCLUSTERED INDEX [Id_UNIQUE] ON [Student] ([id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
GO
  CREATE NONCLUSTERED INDEX [fk_dm_Student_PokójId_idx] ON [Student] ([PokójId] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
CREATE UNIQUE NONCLUSTERED INDEX [Id_UNIQUE] ON [Pokój] ([id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
CREATE UNIQUE NONCLUSTERED INDEX [Id_UNIQUE] ON [Studentka] ([id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
GO
  CREATE NONCLUSTERED INDEX [fk_dm_Studentka_RoomId_idx] ON [Studentka] ([RoomId] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
CREATE UNIQUE NONCLUSTERED INDEX [Id_UNIQUE] ON [Room] ([id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
ALTER TABLE
  [Student] WITH CHECK
ADD
  CONSTRAINT [fk_Student_PokójId] FOREIGN KEY([PokójId]) REFERENCES [dbo].[Pokój]([id]);
GO
ALTER TABLE
  [Student] CHECK CONSTRAINT [fk_Student_PokójId];
ALTER TABLE
  [Studentka] WITH CHECK
ADD
  CONSTRAINT [fk_Studentka_RoomId] FOREIGN KEY([RoomId]) REFERENCES [dbo].[Room]([id]);
GO
ALTER TABLE
  [Studentka] CHECK CONSTRAINT [fk_Studentka_RoomId];