USE master
GO
  CREATE DATABASE DatabaseName COLLATE SQL_Latin1_General_CP1_CI_AS
GO
  USE DatabaseName
GO
  CREATE TABLE [dbo].[Entity1] (
    [Id] INT NOT NULL IDENTITY (1, 1),
    [Entity2Id] INT,
    CONSTRAINT [PK_Entity1] PRIMARY KEY CLUSTERED (
      [Id] ASC
    ) WITH (
      PAD_INDEX = OFF,
      STATISTICS_NORECOMPUTE = OFF,
      IGNORE_DUP_KEY = OFF,
      ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON
    ) ON [PRIMARY]
  ) ON [PRIMARY]
GO
  CREATE TABLE [dbo].[Entity2] (
    [Id] INT NOT NULL IDENTITY (1, 1),
    CONSTRAINT [PK_Entity2] PRIMARY KEY CLUSTERED (
      [Id] ASC
    ) WITH (
      PAD_INDEX = OFF,
      STATISTICS_NORECOMPUTE = OFF,
      IGNORE_DUP_KEY = OFF,
      ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON
    ) ON [PRIMARY]
  ) ON [PRIMARY]
GO
  CREATE TABLE [dbo].[Entity3] (
    [Id] INT NOT NULL IDENTITY (1, 1),
    [Entity4Id] INT NOT NULL,
    CONSTRAINT [PK_Entity3] PRIMARY KEY CLUSTERED (
      [Id] ASC
    ) WITH (
      PAD_INDEX = OFF,
      STATISTICS_NORECOMPUTE = OFF,
      IGNORE_DUP_KEY = OFF,
      ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON
    ) ON [PRIMARY]
  ) ON [PRIMARY]
GO
  CREATE TABLE [dbo].[Entity4] (
    [Id] INT NOT NULL IDENTITY (1, 1),
    CONSTRAINT [PK_Entity4] PRIMARY KEY CLUSTERED (
      [Id] ASC
    ) WITH (
      PAD_INDEX = OFF,
      STATISTICS_NORECOMPUTE = OFF,
      IGNORE_DUP_KEY = OFF,
      ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON
    ) ON [PRIMARY]
  ) ON [PRIMARY]
GO
  CREATE TABLE [dbo].[Entity5] (
    [Id] INT NOT NULL IDENTITY (1, 1),
    [Entity6Id] INT,
    CONSTRAINT [PK_Entity5] PRIMARY KEY CLUSTERED (
      [Id] ASC
    ) WITH (
      PAD_INDEX = OFF,
      STATISTICS_NORECOMPUTE = OFF,
      IGNORE_DUP_KEY = OFF,
      ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON
    ) ON [PRIMARY]
  ) ON [PRIMARY]
GO
  CREATE TABLE [dbo].[Entity6] (
    [Id] INT NOT NULL IDENTITY (1, 1),
    CONSTRAINT [PK_Entity6] PRIMARY KEY CLUSTERED (
      [Id] ASC
    ) WITH (
      PAD_INDEX = OFF,
      STATISTICS_NORECOMPUTE = OFF,
      IGNORE_DUP_KEY = OFF,
      ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON
    ) ON [PRIMARY]
  ) ON [PRIMARY]
GO
  CREATE TABLE [dbo].[Entity7] (
    [Id] INT NOT NULL IDENTITY (1, 1),
    CONSTRAINT [PK_Entity7] PRIMARY KEY CLUSTERED (
      [Id] ASC
    ) WITH (
      PAD_INDEX = OFF,
      STATISTICS_NORECOMPUTE = OFF,
      IGNORE_DUP_KEY = OFF,
      ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON
    ) ON [PRIMARY]
  ) ON [PRIMARY]
GO
  CREATE TABLE [dbo].[Entity8] (
    [Id] INT NOT NULL IDENTITY (1, 1),
    [Entity7Id] INT NOT NULL,
    CONSTRAINT [PK_Entity8] PRIMARY KEY CLUSTERED (
      [Id] ASC
    ) WITH (
      PAD_INDEX = OFF,
      STATISTICS_NORECOMPUTE = OFF,
      IGNORE_DUP_KEY = OFF,
      ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON
    ) ON [PRIMARY]
  ) ON [PRIMARY]
GO
  CREATE TABLE [dbo].[Entity9] (
    [Id] INT NOT NULL IDENTITY (1, 1),
    CONSTRAINT [PK_Entity9] PRIMARY KEY CLUSTERED (
      [Id] ASC
    ) WITH (
      PAD_INDEX = OFF,
      STATISTICS_NORECOMPUTE = OFF,
      IGNORE_DUP_KEY = OFF,
      ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON
    ) ON [PRIMARY]
  ) ON [PRIMARY]
GO
  CREATE TABLE [dbo].[Entity10] (
    [Id] INT NOT NULL IDENTITY (1, 1),
    [Entity9Id] INT,
    CONSTRAINT [PK_Entity10] PRIMARY KEY CLUSTERED (
      [Id] ASC
    ) WITH (
      PAD_INDEX = OFF,
      STATISTICS_NORECOMPUTE = OFF,
      IGNORE_DUP_KEY = OFF,
      ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON
    ) ON [PRIMARY]
  ) ON [PRIMARY]
GO
  CREATE TABLE [dbo].[Entity11] (
    [Id] INT NOT NULL IDENTITY (1, 1),
    CONSTRAINT [PK_Entity11] PRIMARY KEY CLUSTERED (
      [Id] ASC
    ) WITH (
      PAD_INDEX = OFF,
      STATISTICS_NORECOMPUTE = OFF,
      IGNORE_DUP_KEY = OFF,
      ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON
    ) ON [PRIMARY]
  ) ON [PRIMARY]
GO
  CREATE TABLE [dbo].[Entity12] (
    [Id] INT NOT NULL IDENTITY (1, 1),
    CONSTRAINT [PK_Entity12] PRIMARY KEY CLUSTERED (
      [Id] ASC
    ) WITH (
      PAD_INDEX = OFF,
      STATISTICS_NORECOMPUTE = OFF,
      IGNORE_DUP_KEY = OFF,
      ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON
    ) ON [PRIMARY]
  ) ON [PRIMARY]
GO
  CREATE TABLE [dbo].[Entity13] (
    [Id] INT NOT NULL IDENTITY (1, 1),
    [Entity14Id] INT NOT NULL,
    CONSTRAINT [PK_Entity13] PRIMARY KEY CLUSTERED (
      [Id] ASC
    ) WITH (
      PAD_INDEX = OFF,
      STATISTICS_NORECOMPUTE = OFF,
      IGNORE_DUP_KEY = OFF,
      ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON
    ) ON [PRIMARY]
  ) ON [PRIMARY]
GO
  CREATE TABLE [dbo].[Entity14] (
    [Id] INT NOT NULL IDENTITY (1, 1),
    CONSTRAINT [PK_Entity14] PRIMARY KEY CLUSTERED (
      [Id] ASC
    ) WITH (
      PAD_INDEX = OFF,
      STATISTICS_NORECOMPUTE = OFF,
      IGNORE_DUP_KEY = OFF,
      ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON
    ) ON [PRIMARY]
  ) ON [PRIMARY]
GO
  CREATE TABLE [dbo].[Entity15] (
    [Id] INT NOT NULL IDENTITY (1, 1),
    [Entity16Id] INT,
    CONSTRAINT [PK_Entity15] PRIMARY KEY CLUSTERED (
      [Id] ASC
    ) WITH (
      PAD_INDEX = OFF,
      STATISTICS_NORECOMPUTE = OFF,
      IGNORE_DUP_KEY = OFF,
      ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON
    ) ON [PRIMARY]
  ) ON [PRIMARY]
GO
  CREATE TABLE [dbo].[Entity16] (
    [Id] INT NOT NULL IDENTITY (1, 1),
    CONSTRAINT [PK_Entity16] PRIMARY KEY CLUSTERED (
      [Id] ASC
    ) WITH (
      PAD_INDEX = OFF,
      STATISTICS_NORECOMPUTE = OFF,
      IGNORE_DUP_KEY = OFF,
      ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON
    ) ON [PRIMARY]
  ) ON [PRIMARY]
GO
  CREATE TABLE [dbo].[Entity17] (
    [Id] INT NOT NULL IDENTITY (1, 1),
    CONSTRAINT [PK_Entity17] PRIMARY KEY CLUSTERED (
      [Id] ASC
    ) WITH (
      PAD_INDEX = OFF,
      STATISTICS_NORECOMPUTE = OFF,
      IGNORE_DUP_KEY = OFF,
      ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON
    ) ON [PRIMARY]
  ) ON [PRIMARY]
GO
  CREATE TABLE [dbo].[Entity18] (
    [Id] INT NOT NULL IDENTITY (1, 1),
    CONSTRAINT [PK_Entity18] PRIMARY KEY CLUSTERED (
      [Id] ASC
    ) WITH (
      PAD_INDEX = OFF,
      STATISTICS_NORECOMPUTE = OFF,
      IGNORE_DUP_KEY = OFF,
      ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON
    ) ON [PRIMARY]
  ) ON [PRIMARY]
GO
  CREATE TABLE [dbo].[rl_Entity11_relation name_Entity12] (
    [Id] INT NOT NULL IDENTITY (1, 1),
    [Entity11Id] INT NOT NULL,
    [Entity12Id] INT NOT NULL,
    CONSTRAINT [PK_rl_Entity11_relation name_Entity12] PRIMARY KEY CLUSTERED (
      [Id] ASC
    ) WITH (
      PAD_INDEX = OFF,
      STATISTICS_NORECOMPUTE = OFF,
      IGNORE_DUP_KEY = OFF,
      ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON
    ) ON [PRIMARY]
  ) ON [PRIMARY]
GO
  CREATE TABLE [dbo].[rl_Entity17_relation name_Entity18] (
    [Id] INT NOT NULL IDENTITY (1, 1),
    [Entity17Id] INT NOT NULL,
    [Entity18Id] INT NOT NULL,
    CONSTRAINT [PK_rl_Entity17_relation name_Entity18] PRIMARY KEY CLUSTERED (
      [Id] ASC
    ) WITH (
      PAD_INDEX = OFF,
      STATISTICS_NORECOMPUTE = OFF,
      IGNORE_DUP_KEY = OFF,
      ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON
    ) ON [PRIMARY]
  ) ON [PRIMARY]
GO
  CREATE UNIQUE NONCLUSTERED INDEX [Id_UNIQUE] ON [Entity1] ([id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
GO
  CREATE NONCLUSTERED INDEX [fk_dm_Entity1_Entity2Id_idx] ON [Entity1] ([Entity2Id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
CREATE UNIQUE NONCLUSTERED INDEX [Id_UNIQUE] ON [Entity2] ([id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
CREATE UNIQUE NONCLUSTERED INDEX [Id_UNIQUE] ON [Entity3] ([id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
GO
  CREATE NONCLUSTERED INDEX [fk_dm_Entity3_Entity4Id_idx] ON [Entity3] ([Entity4Id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
CREATE UNIQUE NONCLUSTERED INDEX [Id_UNIQUE] ON [Entity4] ([id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
CREATE UNIQUE NONCLUSTERED INDEX [Id_UNIQUE] ON [Entity5] ([id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
GO
  CREATE NONCLUSTERED INDEX [fk_dm_Entity5_Entity6Id_idx] ON [Entity5] ([Entity6Id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
CREATE UNIQUE NONCLUSTERED INDEX [Id_UNIQUE] ON [Entity6] ([id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
CREATE UNIQUE NONCLUSTERED INDEX [Id_UNIQUE] ON [Entity7] ([id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
CREATE UNIQUE NONCLUSTERED INDEX [Id_UNIQUE] ON [Entity8] ([id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
GO
  CREATE NONCLUSTERED INDEX [fk_dm_Entity8_Entity7Id_idx] ON [Entity8] ([Entity7Id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
CREATE UNIQUE NONCLUSTERED INDEX [Id_UNIQUE] ON [Entity9] ([id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
CREATE UNIQUE NONCLUSTERED INDEX [Id_UNIQUE] ON [Entity10] ([id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
GO
  CREATE NONCLUSTERED INDEX [fk_dm_Entity10_Entity9Id_idx] ON [Entity10] ([Entity9Id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
CREATE UNIQUE NONCLUSTERED INDEX [Id_UNIQUE] ON [Entity11] ([id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
CREATE UNIQUE NONCLUSTERED INDEX [Id_UNIQUE] ON [Entity12] ([id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
CREATE UNIQUE NONCLUSTERED INDEX [Id_UNIQUE] ON [Entity13] ([id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
GO
  CREATE NONCLUSTERED INDEX [fk_dm_Entity13_Entity14Id_idx] ON [Entity13] ([Entity14Id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
CREATE UNIQUE NONCLUSTERED INDEX [Id_UNIQUE] ON [Entity14] ([id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
CREATE UNIQUE NONCLUSTERED INDEX [Id_UNIQUE] ON [Entity15] ([id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
GO
  CREATE NONCLUSTERED INDEX [fk_dm_Entity15_Entity16Id_idx] ON [Entity15] ([Entity16Id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
CREATE UNIQUE NONCLUSTERED INDEX [Id_UNIQUE] ON [Entity16] ([id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
CREATE UNIQUE NONCLUSTERED INDEX [Id_UNIQUE] ON [Entity17] ([id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
CREATE UNIQUE NONCLUSTERED INDEX [Id_UNIQUE] ON [Entity18] ([id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
CREATE UNIQUE NONCLUSTERED INDEX [Id_UNIQUE] ON [rl_Entity11_relation name_Entity12] ([id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
GO
  CREATE NONCLUSTERED INDEX [fk_dm_rl_Entity11_relation name_Entity12_Entity11Id_idx] ON [rl_Entity11_relation name_Entity12] ([Entity11Id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
GO
  CREATE NONCLUSTERED INDEX [fk_dm_rl_Entity11_relation name_Entity12_Entity12Id_idx] ON [rl_Entity11_relation name_Entity12] ([Entity12Id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
CREATE UNIQUE NONCLUSTERED INDEX [Id_UNIQUE] ON [rl_Entity17_relation name_Entity18] ([id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
GO
  CREATE NONCLUSTERED INDEX [fk_dm_rl_Entity17_relation name_Entity18_Entity17Id_idx] ON [rl_Entity17_relation name_Entity18] ([Entity17Id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
GO
  CREATE NONCLUSTERED INDEX [fk_dm_rl_Entity17_relation name_Entity18_Entity18Id_idx] ON [rl_Entity17_relation name_Entity18] ([Entity18Id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    DROP_EXISTING = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
ALTER TABLE
  [Entity1] WITH CHECK
ADD
  CONSTRAINT [fk_Entity1_Entity2Id] FOREIGN KEY([Entity2Id]) REFERENCES [dbo].[Entity2]([Id]);
GO
ALTER TABLE
  [Entity1] CHECK CONSTRAINT [fk_Entity1_Entity2Id];
ALTER TABLE
  [Entity3] WITH CHECK
ADD
  CONSTRAINT [fk_Entity3_Entity4Id] FOREIGN KEY([Entity4Id]) REFERENCES [dbo].[Entity4]([Id]);
GO
ALTER TABLE
  [Entity3] CHECK CONSTRAINT [fk_Entity3_Entity4Id];
ALTER TABLE
  [Entity5] WITH CHECK
ADD
  CONSTRAINT [fk_Entity5_Entity6Id] FOREIGN KEY([Entity6Id]) REFERENCES [dbo].[Entity6]([Id]);
GO
ALTER TABLE
  [Entity5] CHECK CONSTRAINT [fk_Entity5_Entity6Id];
ALTER TABLE
  [Entity8] WITH CHECK
ADD
  CONSTRAINT [fk_Entity8_Entity7Id] FOREIGN KEY([Entity7Id]) REFERENCES [dbo].[Entity7]([Id]);
GO
ALTER TABLE
  [Entity8] CHECK CONSTRAINT [fk_Entity8_Entity7Id];
ALTER TABLE
  [Entity10] WITH CHECK
ADD
  CONSTRAINT [fk_Entity10_Entity9Id] FOREIGN KEY([Entity9Id]) REFERENCES [dbo].[Entity9]([Id]);
GO
ALTER TABLE
  [Entity10] CHECK CONSTRAINT [fk_Entity10_Entity9Id];
ALTER TABLE
  [Entity13] WITH CHECK
ADD
  CONSTRAINT [fk_Entity13_Entity14Id] FOREIGN KEY([Entity14Id]) REFERENCES [dbo].[Entity14]([Id]);
GO
ALTER TABLE
  [Entity13] CHECK CONSTRAINT [fk_Entity13_Entity14Id];
ALTER TABLE
  [Entity15] WITH CHECK
ADD
  CONSTRAINT [fk_Entity15_Entity16Id] FOREIGN KEY([Entity16Id]) REFERENCES [dbo].[Entity16]([Id]);
GO
ALTER TABLE
  [Entity15] CHECK CONSTRAINT [fk_Entity15_Entity16Id];
ALTER TABLE
  [rl_Entity11_relation name_Entity12] WITH CHECK
ADD
  CONSTRAINT [fk_rl_Entity11_relation name_Entity12_Entity11Id] FOREIGN KEY([Entity11Id]) REFERENCES [dbo].[Entity12]([Id]);
GO
ALTER TABLE
  [rl_Entity11_relation name_Entity12] CHECK CONSTRAINT [fk_rl_Entity11_relation name_Entity12_Entity11Id];
ALTER TABLE
  [rl_Entity11_relation name_Entity12] WITH CHECK
ADD
  CONSTRAINT [fk_rl_Entity11_relation name_Entity12_Entity12Id] FOREIGN KEY([Entity12Id]) REFERENCES [dbo].[Entity12]([Id]);
GO
ALTER TABLE
  [rl_Entity11_relation name_Entity12] CHECK CONSTRAINT [fk_rl_Entity11_relation name_Entity12_Entity12Id];
ALTER TABLE
  [rl_Entity17_relation name_Entity18] WITH CHECK
ADD
  CONSTRAINT [fk_rl_Entity17_relation name_Entity18_Entity17Id] FOREIGN KEY([Entity17Id]) REFERENCES [dbo].[rl_Entity11_relation name_Entity12]([Id]);
GO
ALTER TABLE
  [rl_Entity17_relation name_Entity18] CHECK CONSTRAINT [fk_rl_Entity17_relation name_Entity18_Entity17Id];
ALTER TABLE
  [rl_Entity17_relation name_Entity18] WITH CHECK
ADD
  CONSTRAINT [fk_rl_Entity17_relation name_Entity18_Entity18Id] FOREIGN KEY([Entity18Id]) REFERENCES [dbo].[rl_Entity11_relation name_Entity12]([Id]);
GO
ALTER TABLE
  [rl_Entity17_relation name_Entity18] CHECK CONSTRAINT [fk_rl_Entity17_relation name_Entity18_Entity18Id];